// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqliteDB

type User struct {
	ID            int64   `json:"id"`
	Email         string  `json:"email"`
	PasswordHash  *string `json:"passwordHash"`
	Role          string  `json:"role"`
	Claims        *string `json:"claims"`
	OauthProvider *string `json:"oauthProvider"`
	OauthID       *string `json:"oauthId"`
	CreatedAt     int64   `json:"createdAt"`
	UpdatedAt     int64   `json:"updatedAt"`
	IsActive      bool    `json:"isActive"`
}
